--number of deals wons
select
    count(opportunity_id) as total_won_deal
from
    sales_pipeline
where
    deal_stage = "Won";

--4238
--No of deals lost
select
    count(opportunity_id) as total_lost_deal
from
    sales_pipeline
where
    deal_stage = "lost";

--no of engaging deal(stale deals)
select
    count(opportunity_id) as total_engaging_deal
from
    sales_pipeline
where
    deal_stage = "Engaging";

--prospecting deals
select
    count(opportunity_id) as total_prospecting_deal
from
    sales_pipeline
where
    deal_stage = "prospecting";

--deals won by each agent
select
    sales_agent,
    count(sales_agent) as sales_by_agent
from
    sales_pipeline
where
    deal_stage = "won"
group by
    sales_agent
order by
    sales_by_agent desc;

--deals lost by each agent
select
    sales_agent,
    count(sales_agent) as sales_by_agent
from
    sales_pipeline
where
    deal_stage = "lost"
group by
    sales_agent
order by
    sales_by_agent desc;

--conversion rate
select
    sum(
        case
            when deal_stage = 'Won' then 1
            else 0
        end
    ) * 1.0 / count(opportunity_id) as conversion_rate
from
    sales_pipeline;

--lost rate
select
    SUM(deal_stage = 'Lost') / COUNT(*) AS loss_rate
from
    sales_pipeline;

--revenue generated by each account
select
    account,
    sum(revenue) as total_revenue
from
    accounts
group by
    account
order by
    total_revenue DESC
    --revenue generated by agents
SELECT
    sales_agent,
    COUNT(*) AS total_deals,
    SUM(deal_stage = 'Won') AS won_deals,
    SUM(deal_stage = 'Lost') AS lost_deals,
    SUM(
        CASE
            WHEN deal_stage = 'Won' THEN close_value
            ELSE 0
        END
    ) AS revenue_generated
FROM
    sales_pipeline
GROUP BY
    sales_agent
ORDER BY
    revenue_generated DESC;

--revenue generated by accounts
SELECT
    account,
    COUNT(*) AS total_deals,
    SUM(deal_stage = 'Won') AS won_deals,
    SUM(deal_stage = 'Lost') AS lost_deals,
    SUM(
        CASE
            WHEN deal_stage = 'Won' THEN close_value
            ELSE 0
        END
    ) AS revenue_generated
FROM
    sales_pipeline
GROUP BY
    account
ORDER BY
    revenue_generated DESC;

--Conversion rate per sales agent
SELECT
    sales_agent,
    COUNT(*) AS total_deals,
    SUM(deal_stage = 'Won') AS won_deals,
    SUM(deal_stage = 'Won') * 1.0 / COUNT(*) AS conversion_rate,
    SUM(
        CASE
            WHEN deal_stage = 'Won' THEN close_value
            ELSE 0
        END
    ) AS revenue
FROM
    sales_pipeline
GROUP BY
    sales_agent
ORDER BY
    conversion_rate DESC;

--revenue generated by product
select
    product,
    sum(close_value) as revenue
from
    sales_pipeline
group by
    product
order by
    revenue desc
    --monthly revenue
SELECT
    MONTHNAME (close_date) AS month_name,
    YEAR (close_date) AS sales_year,
    SUM(close_value) AS monthly_revenue
FROM
    sales_pipeline
WHERE
    deal_stage = 'Won'
GROUP BY
    sales_year,
    month_name
ORDER BY
    monthly_revenue DESC;

--slow deals
SELECT
    opportunity_id,
    sales_agent,
    engage_date,
    close_date,
    DATEDIFF (close_date, engage_date) AS days_to_finish
FROM
    sales_pipeline
WHERE
    deal_stage = 'Won'
ORDER BY
    days_to_finish DESC;